version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

commands:
  deploy-env:
    description: "Sets ecs-deploy to update a service with a target docker image"
    parameters:
      service-name:
        type: string
      image-tag:
        type: string
      cluster-name:
        type: string
    steps:
      - run:
          name: Install ecs deploy
          command: |
            sudo pip install ecs-deploy
      - run:
          name: Premote target image
          command: |
            ecs deploy \
            --no-deregister \
            --access-key-id $AWS_ID_KEY \
            --secret-access-key $AWS_SECRET_KEY \
            --timeout 1800 \
            --region $AWS_REGION \       
            << parameters.service-name >> \
            -t << parameters.image-tag >> \
            << parameters.cluster-name >> 
          no_output_timeout: 30m

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - aws-ecr/ecr-login
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build customer-information-api-test
      - run:
          name: Run tests
          command: docker-compose up customer-information-api-test

  deploy-to-development:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'customer-api-development'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"
          cluster-name: "$CLUSTER_DEVELOPMENT"

  deploy-to-staging:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'customer-information-api-staging'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"
          cluster-name: "$CLUSTER_STAGING"

  deploy-to-production:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'customer-information-api-production'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"
          cluster-name: "$CLUSTER_PRODUCTION"

workflows:
  build-and-deploy:
      jobs:
      - check
      - aws-ecr/build_and_push_image:
          name: build_and_push_image
          dockerfile: ./customer-information-api/Dockerfile
          path: ./customer-information-api
          account-url: AWS_ECR_HOST
          repo: $AWS_ECR_PATH
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master

      - deploy-to-development:
          requires:
            - check
            - build_and_push_image
          filters:
            branches:
              only: master

      - permit-staging-release:
          type: approval
          requires:
            - deploy-to-development
          filters:
            branches:
              only: master

      - deploy-to-staging:
          requires:
            - permit-staging-release
          filters:
            branches:
              only: master

      - permit-production-release:
          type: approval
          requires:
            - deploy-to-staging
          filters:
            branches:
              only: master

      - deploy-to-production:
          requires:
            - permit-production-release
          filters:
            branches:
              only: master
